import {
    BILLING_STEP as SOURCE_BILLING_STEP,
    CHECKOUT_URL,
    DETAILS_STEP as SOURCE_DETAILS_STEP,
    PAYMENT_TOTALS,
    SHIPPING_STEP as SOURCE_SHIPPING_STEP,
    UPDATE_EMAIL_CHECK_FREQUENCY
} from 'SourceRoute/Checkout/Checkout.config';

export {
    CHECKOUT_URL,
    PAYMENT_TOTALS,
    UPDATE_EMAIL_CHECK_FREQUENCY
};

// TODO: implement SHIPPING_STEP
export const SHIPPING_STEP = SOURCE_SHIPPING_STEP;

// TODO: implement BILLING_STEP
export const BILLING_STEP = SOURCE_BILLING_STEP;

// TODO: implement DETAILS_STEP
export const DETAILS_STEP = SOURCE_DETAILS_STEP;
